ssage: * New upstream version:   - Support runtime font configuration changes   - Use GIO for mime information   - Use GIO directly for the file chooser, do not load filesystem     implementation modules. This change causes some regressions on Win32,     which will be addressed by improved Win32 support in GIO.   - GTK+ no longer uses translations when the application is not     translated to the current locale   - Bugs fixed:   520874 Should use gio directly   536185 monitor font configuration   536757 openoffice.org menus are placed at wrong position   536990 updateiconcache.c: 'close ()' is redundant   535608 do not string-copy accel paths in the menu code   488119 critical warnings from gtk_tree_view_get_visible_range   536730 memory corruption in gtktreeview   131920 gtkNotebook sends incorrect switch_page value   526987 GtkCellRendererCombo should allow model to be NULL   536765 GtkComboBox should set COMBO type hint for its menu   503071 Application direction changes to right to left even if...   517706 Connecting GtkButton with "use-stock" == FALSE to a...   519092 Add accessibility support to GtkVolumeButton   524222 GtkToolbar with mix of buttons with and without icons...   537985 gtk_init_with_args() doesn't open a display after...   531960 crash in eog-image.c:1154:   408154 Change GtkEntryCompletion max-items to style property...   506853 gtk_tree_view_enable_model_drag_[source|dest] problem   536430 Libs and Cflags paths in gail-uninstalled.pc.in are out o...   537685 print to file crashes when the target can not be written * debian/control.in:   - build-depends on libxrandr-dev   - updated glib, pango, atk, cairo requirements   - use conflicts and replaces on the different libgail binaries since the     library is in gtk now * debian/libgtk2.0-0.install.in:   - updated for the new version changes * debian/patches/009_gtk-export-filechooser.patch:   - updated to apply but it might require other changes to work correctly * debian/patches/020_immodules-files-d.patch,   debian/patches/021_loader-files-d.patch,   debian/patches/070_mandatory-relibtoolize.patch:   - new version update * debian/patches/071_correct_directfb_declarations.patch:   - rename functions for the offscreen rendering changes * debian/patches/072_workaround_directfb_build.patch:   - don't use an incorrect structure variable to fix build issue * debian/patches/092_openoffice-menus.patch,   debian/patches/095_gtk-im-module-setting.patch:   - those changes are in the new version * debian/rules:   - don't use the print backend test configure option so it breaks the build   - update shlibs version   - use --without-libjasper for now since the option breaks the build ---------------------------------------------------------- e --include-merged or -n0 to see merged revisions.
original bzr status:
revno: 80 [merge]
author: Sebastien Bacher <seb128@canonical.com>
committer: Bazaar Package Importer <james.westby@ubuntu.com>
branch nick: intrepid

diff --git a/modules/printbackends/lpr/Makefile.in b/modules/printbackends/lpr/Makefile.in
--- a/modules/printbackends/lpr/Makefile.in
+++ b/modules/printbackends/lpr/Makefile.in
@@ -14,6 +14,8 @@
 
 @SET_MAKE@
 
+# GTK+ - The GIMP Toolkit
+
 srcdir = @srcdir@
 top_srcdir = @top_srcdir@
 VPATH = @srcdir@
@@ -51,6 +53,8 @@ BASE_DEPENDENCIES_CFLAGS = @BASE_DEPENDENCIES_CFLAGS@
 BASE_DEPENDENCIES_LIBS = @BASE_DEPENDENCIES_LIBS@
 BUILD_DYNAMIC_MODULES_FALSE = @BUILD_DYNAMIC_MODULES_FALSE@
 BUILD_DYNAMIC_MODULES_TRUE = @BUILD_DYNAMIC_MODULES_TRUE@
+BUILD_GDIPLUS_LOADERS_FALSE = @BUILD_GDIPLUS_LOADERS_FALSE@
+BUILD_GDIPLUS_LOADERS_TRUE = @BUILD_GDIPLUS_LOADERS_TRUE@
 CAIRO_PREFIX = @CAIRO_PREFIX@
 CATALOGS = @CATALOGS@
 CATOBJEXT = @CATOBJEXT@
@@ -93,6 +97,9 @@ ENABLE_MAN_TRUE = @ENABLE_MAN_TRUE@
 EXEEXT = @EXEEXT@
 F77 = @F77@
 FFLAGS = @FFLAGS@
+GAIL_INET_LIBS = @GAIL_INET_LIBS@
+GAIL_LT_CURRENT_MINUS_AGE = @GAIL_LT_CURRENT_MINUS_AGE@
+GAIL_LT_VERSION_INFO = @GAIL_LT_VERSION_INFO@
 GDK_DEP_CFLAGS = @GDK_DEP_CFLAGS@
 GDK_DEP_LIBS = @GDK_DEP_LIBS@
 GDK_EXTRA_CFLAGS = @GDK_EXTRA_CFLAGS@
@@ -150,6 +157,10 @@ HAVE_CXX_TRUE = @HAVE_CXX_TRUE@
 HAVE_DOCBOOK_FALSE = @HAVE_DOCBOOK_FALSE@
 HAVE_DOCBOOK_TRUE = @HAVE_DOCBOOK_TRUE@
 HAVE_HTTP_AUTHSTRING = @HAVE_HTTP_AUTHSTRING@
+HAVE_INCLUDED_IMMMODULES_FALSE = @HAVE_INCLUDED_IMMMODULES_FALSE@
+HAVE_INCLUDED_IMMMODULES_TRUE = @HAVE_INCLUDED_IMMMODULES_TRUE@
+HAVE_JASPER_FALSE = @HAVE_JASPER_FALSE@
+HAVE_JASPER_TRUE = @HAVE_JASPER_TRUE@
 HAVE_JPEG_FALSE = @HAVE_JPEG_FALSE@
 HAVE_JPEG_TRUE = @HAVE_JPEG_TRUE@
 HAVE_OBJC_FALSE = @HAVE_OBJC_FALSE@
@@ -161,16 +172,48 @@ HAVE_TIFF_TRUE = @HAVE_TIFF_TRUE@
 HAVE_X11R6_FALSE = @HAVE_X11R6_FALSE@
 HAVE_X11R6_TRUE = @HAVE_X11R6_TRUE@
 HTML_DIR = @HTML_DIR@
+INCLUDED_IMMODULE_DEFINE = @INCLUDED_IMMODULE_DEFINE@
+INCLUDED_IMMODULE_OBJ = @INCLUDED_IMMODULE_OBJ@
 INCLUDED_LOADER_DEFINE = @INCLUDED_LOADER_DEFINE@
 INCLUDED_LOADER_OBJ = @INCLUDED_LOADER_OBJ@
 INCLUDE_ANI_FALSE = @INCLUDE_ANI_FALSE@
 INCLUDE_ANI_TRUE = @INCLUDE_ANI_TRUE@
 INCLUDE_BMP_FALSE = @INCLUDE_BMP_FALSE@
 INCLUDE_BMP_TRUE = @INCLUDE_BMP_TRUE@
+INCLUDE_GDIPLUS_FALSE = @INCLUDE_GDIPLUS_FALSE@
+INCLUDE_GDIPLUS_TRUE = @INCLUDE_GDIPLUS_TRUE@
 INCLUDE_GIF_FALSE = @INCLUDE_GIF_FALSE@
 INCLUDE_GIF_TRUE = @INCLUDE_GIF_TRUE@
+INCLUDE_ICNS_FALSE = @INCLUDE_ICNS_FALSE@
+INCLUDE_ICNS_TRUE = @INCLUDE_ICNS_TRUE@
 INCLUDE_ICO_FALSE = @INCLUDE_ICO_FALSE@
 INCLUDE_ICO_TRUE = @INCLUDE_ICO_TRUE@
+INCLUDE_IM_AM_ET_FALSE = @INCLUDE_IM_AM_ET_FALSE@
+INCLUDE_IM_AM_ET_TRUE = @INCLUDE_IM_AM_ET_TRUE@
+INCLUDE_IM_CEDILLA_FALSE = @INCLUDE_IM_CEDILLA_FALSE@
+INCLUDE_IM_CEDILLA_TRUE = @INCLUDE_IM_CEDILLA_TRUE@
+INCLUDE_IM_CYRILLIC_TRANSLIT_FALSE = @INCLUDE_IM_CYRILLIC_TRANSLIT_FALSE@
+INCLUDE_IM_CYRILLIC_TRANSLIT_TRUE = @INCLUDE_IM_CYRILLIC_TRANSLIT_TRUE@
+INCLUDE_IM_IME_FALSE = @INCLUDE_IM_IME_FALSE@
+INCLUDE_IM_IME_TRUE = @INCLUDE_IM_IME_TRUE@
+INCLUDE_IM_INUKTITUT_FALSE = @INCLUDE_IM_INUKTITUT_FALSE@
+INCLUDE_IM_INUKTITUT_TRUE = @INCLUDE_IM_INUKTITUT_TRUE@
+INCLUDE_IM_IPA_FALSE = @INCLUDE_IM_IPA_FALSE@
+INCLUDE_IM_IPA_TRUE = @INCLUDE_IM_IPA_TRUE@
+INCLUDE_IM_MULTIPRESS_FALSE = @INCLUDE_IM_MULTIPRESS_FALSE@
+INCLUDE_IM_MULTIPRESS_TRUE = @INCLUDE_IM_MULTIPRESS_TRUE@
+INCLUDE_IM_THAI_FALSE = @INCLUDE_IM_THAI_FALSE@
+INCLUDE_IM_THAI_TRUE = @INCLUDE_IM_THAI_TRUE@
+INCLUDE_IM_TI_ER_FALSE = @INCLUDE_IM_TI_ER_FALSE@
+INCLUDE_IM_TI_ER_TRUE = @INCLUDE_IM_TI_ER_TRUE@
+INCLUDE_IM_TI_ET_FALSE = @INCLUDE_IM_TI_ET_FALSE@
+INCLUDE_IM_TI_ET_TRUE = @INCLUDE_IM_TI_ET_TRUE@
+INCLUDE_IM_VIQR_FALSE = @INCLUDE_IM_VIQR_FALSE@
+INCLUDE_IM_VIQR_TRUE = @INCLUDE_IM_VIQR_TRUE@
+INCLUDE_IM_XIM_FALSE = @INCLUDE_IM_XIM_FALSE@
+INCLUDE_IM_XIM_TRUE = @INCLUDE_IM_XIM_TRUE@
+INCLUDE_JASPER_FALSE = @INCLUDE_JASPER_FALSE@
+INCLUDE_JASPER_TRUE = @INCLUDE_JASPER_TRUE@
 INCLUDE_JPEG_FALSE = @INCLUDE_JPEG_FALSE@
 INCLUDE_JPEG_TRUE = @INCLUDE_JPEG_TRUE@
 INCLUDE_PCX_FALSE = @INCLUDE_PCX_FALSE@
@@ -199,6 +242,7 @@ INSTALL_STRIP_PROGRAM = @INSTALL_STRIP_PROGRAM@
 INSTOBJEXT = @INSTOBJEXT@
 INTLLIBS = @INTLLIBS@
 LDFLAGS = @LDFLAGS@
+LIBJASPER = @LIBJASPER@
 LIBJPEG = @LIBJPEG@
 LIBOBJS = @LIBOBJS@
 LIBPNG = @LIBPNG@
@@ -330,6 +374,38 @@ sbindir = @sbindir@
 sharedstatedir = @sharedstatedir@
 sysconfdir = @sysconfdir@
 target_alias = @target_alias@
+
+GTESTER = gtester		# in $PATH for non-GLIB packages
+GTESTER_REPORT = gtester-report		# in $PATH for non-GLIB packages
+
+# initialize variables for unconditional += appending
+EXTRA_DIST = 
+TEST_PROGS = 
+
+### testing rules
+
+# Xvfb based test rules
+XVFB = Xvfb -screen 0 800x600x16
+XIDS = 101 102 103 104 105 106 107 197 199 211 223 227 293 307 308 309 310 311 \
+   491 492 493 494 495 496 497 498 499 500 501 502 503 504 505 506 507 508 509 \
+   991 992 993 994 995 996 997 998 999 1000 1001 1002 1003 1004 1005 1006 1007 \
+  1008 1009 4703 4721 4723 4729 4733 4751 9973 9974 9975 9976 9977 9978 9979 \
+  9980 9981 9982 9983 9984 9985 9986 9987 9988 9989 9990 9991 9992 9993 9994 \
+  9995 9996 9997 9998 9999
+
+SKIP_GDKTARGET = \
+	test "$(gdktarget)" != "x11" \
+	&& echo "Gtk+Tests:INFO: Skipping GUI tests for non-X11 target."
+
+XVFB_START = \
+	${XVFB} -help 2>/dev/null 1>&2 \
+	&& XID=`for id in $(XIDS) ; do test -e /tmp/.X$$id-lock || { echo $$id; exit 0; }; done; exit 1` \
+	&& { ${XVFB} :$$XID -screen 0 800x600x16 -nolisten tcp -auth /dev/null >/dev/null 2>&1 & \
+	       trap "kill -15 $$! " 0 HUP INT QUIT TRAP USR1 PIPE TERM ; } \
+	|| { echo "Gtk+Tests:ERROR: Failed to start Xvfb environment for X11 target tests."; exit 1; } \
+	&& DISPLAY=:$$XID && export DISPLAY
+
+
 @PLATFORM_WIN32_TRUE@no_undefined = -no-undefined
 
 INCLUDES = \
@@ -388,14 +464,15 @@ LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
 DIST_SOURCES = $(libprintbackend_lpr_la_SOURCES)
 HEADERS = $(noinst_HEADERS)
 
-DIST_COMMON = $(noinst_HEADERS) $(srcdir)/Makefile.in Makefile.am
+DIST_COMMON = $(noinst_HEADERS) $(srcdir)/Makefile.in \
+	$(top_srcdir)/Makefile.decl Makefile.am
 SOURCES = $(libprintbackend_lpr_la_SOURCES)
 
 all: all-am
 
 .SUFFIXES:
 .SUFFIXES: .c .lo .o .obj
-$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ Makefile.am  $(top_srcdir)/configure.in $(ACLOCAL_M4)
+$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ Makefile.am $(top_srcdir)/Makefile.decl $(top_srcdir)/configure.in $(ACLOCAL_M4)
 	cd $(top_srcdir) && \
 	  $(AUTOMAKE) --gnu  modules/printbackends/lpr/Makefile
 Makefile: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.in  $(top_builddir)/config.status
@@ -541,6 +618,7 @@ top_distdir = ../../..
 distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)
 
 distdir: $(DISTFILES)
+	$(mkinstalldirs) $(distdir)/../../..
 	@srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`; \
 	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's|.|.|g'`; \
 	list='$(DISTFILES)'; for file in $$list; do \
@@ -568,6 +646,7 @@ distdir: $(DISTFILES)
 	  fi; \
 	done
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-local
 check: check-am
 all-am: Makefile $(LTLIBRARIES) $(HEADERS)
 
@@ -646,7 +725,7 @@ ps-am:
 
 uninstall-am: uninstall-backendLTLIBRARIES uninstall-info-am
 
-.PHONY: CTAGS GTAGS all all-am check check-am clean \
+.PHONY: CTAGS GTAGS all all-am check check-am check-local clean \
 	clean-backendLTLIBRARIES clean-generic clean-libtool ctags \
 	distclean distclean-compile distclean-generic distclean-libtool \
 	distclean-tags distdir dvi dvi-am info info-am install \
@@ -659,6 +738,59 @@ uninstall-am: uninstall-backendLTLIBRARIES uninstall-info-am
 	tags uninstall uninstall-am uninstall-backendLTLIBRARIES \
 	uninstall-info-am
 
+# call as: $(XVFB_START) && someprogram
+
+# test: run all tests in cwd and subdirs
+test:	${TEST_PROGS}
+	@$(SKIP_GDKTARGET) || test -z "${TEST_PROGS}" || { \
+	  $(XVFB_START) && { set -e; ${GTESTER} --verbose ${TEST_PROGS}; }; \
+	}
+	@ for subdir in $(SUBDIRS) ; do \
+	    test "$$subdir" = "." -o "$$subdir" = "po" -o "$$subdir" = "po-properties" || \
+	    ( cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $@ ) || exit $? ; \
+	  done
+# test-report: run tests in subdirs and generate report
+# perf-report: run tests in subdirs with -m perf and generate report
+# full-report: like test-report: with -m perf and -m slow
+test-report perf-report full-report:	${TEST_PROGS}
+	@ ignore_logdir=true ; \
+	  if test -z "$$GTESTER_LOGDIR" ; then \
+	    GTESTER_LOGDIR=`mktemp -d "\`pwd\`/.testlogs-XXXXXX"`; export GTESTER_LOGDIR ; \
+	    ignore_logdir=false ; \
+	  fi ; \
+	  for subdir in $(SUBDIRS) ; do \
+	    test "$$subdir" = "." -o "$$subdir" = "po" -o "$$subdir" = "po-properties" || \
+	    ( cd $$subdir && $(MAKE) $(AM_MAKEFLAGS) $@ ) || exit $? ; \
+	  done ; \
+	  $(SKIP_GDKTARGET) || test -z "${TEST_PROGS}" || { \
+	    case $@ in \
+	    test-report) test_options="-k";; \
+	    perf-report) test_options="-k -m=perf";; \
+	    full-report) test_options="-k -m=perf -m=slow";; \
+	    esac ; \
+	    $(XVFB_START) && { \
+	      set -e; \
+	      if test -z "$$GTESTER_LOGDIR" ; then \
+	        ${GTESTER} --verbose $$test_options -o test-report.xml ${TEST_PROGS} ; \
+	      elif test -n "${TEST_PROGS}" ; then \
+	        ${GTESTER} --verbose $$test_options -o `mktemp "$$GTESTER_LOGDIR/log-XXXXXX"` ${TEST_PROGS} ; \
+	      fi ; \
+	    }; \
+	  }; \
+	  $$ignore_logdir || { \
+	    echo '<?xml version="1.0"?>' > $@.xml ; \
+	    echo '<report-collection>'  >> $@.xml ; \
+	    for lf in `ls -L "$$GTESTER_LOGDIR"/.` ; do \
+	      sed '1,1s/^<?xml\b[^>?]*?>//' <"$$GTESTER_LOGDIR"/"$$lf" >> $@.xml ; \
+	    done ; \
+	    echo >> $@.xml ; \
+	    echo '</report-collection>' >> $@.xml ; \
+	    rm -rf "$$GTESTER_LOGDIR"/ ; \
+	    ${GTESTER_REPORT} --version 2>/dev/null 1>&2 ; test "$$?" != 0 || ${GTESTER_REPORT} $@.xml >$@.html ; \
+	  }
+.PHONY: test test-report perf-report full-report
+# run make test as part of make check
+check-local: test
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
 .NOEXPORT:
